/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.example;

public class Library implements AutoCloseable, Hello {
    
    public void close() {
        System.out.println("CLOSE");
    }

    public void hello() {
        System.out.println("HELLO");
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
